swagger: '2.0'
info:
  description: API Documentation of Comdex custom modules
  title: Comdex Swagger Documentation
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
host: localhost:1317
schemes:
  - http
  - https
tags:
paths:
definitions: