name: Lint
on:
  pull_request:
  push:
    branches:
      - feature/exchange
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERN: |
            .go
            .mod
            .sum
      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          args: -e SA1019 --timeout 10m
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: "env.GIT_DIFF != ''"
